### ISSUE TITLE
Missing spell color

### ISSUE THREAD

**Issue by markand** [arcticicestudio/nord-vim#106]
Hello,

It looks like spell color is missing because I can't see text errors using nord theme.

See using PaperColor:

![papercolor](https://user-images.githubusercontent.com/11919008/37146726-e41c0fe2-22c4-11e8-9265-c9f9d4735bed.png)

And using nord:

![nord](https://user-images.githubusercontent.com/11919008/37146737-eddfa2f0-22c4-11e8-8573-2f70219989f8.png)

**Comment by arcticicestudio** [comment]
@markand Thanks for your contribution :+1: 

@dylnmc Maybe a new theme configuration to allow users to explicitly enable `underlines (including `undercurl`) would be nice (https://github.com/arcticicestudio/nord-vim/issues/105#issuecomment-370399045). I think it should be disabled by default since there are unfortunately still too many terminals without support for it. The default should be then to use the _fg_ style.

**Comment by markand** [comment]
Hello,

Sorry I did not give a lot of information. The screenshots come from vim in GNOME Terminal (which supports underline since some commands like `systemctl`, `hg` or even `man` produce some underlined text). In gvim it works fine as you said using jagged style underline in red.

The snippet **NordFixes** works fine if added before `colorscheme nord`. Thanks :)

**Comment by arcticicestudio** [comment]
Resolved in #127 which superseded #109.
