### ISSUE TITLE
Several highlight groups are not highlighted at all

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#12]
Nord-vim does not highlight `Constant`, `Identifier` and `Special` groups, which makes files of several types less readable when using vim's default syntax files that make use of those groups. Especially `Special` is often used, for example in the default syntax of `awk`.

**Comment by arcticicestudio** [comment]
`Constant` and `Identifier` are highlighted by using the default foreground `nord4`. I've designed it this way because every other group is colored different so the white color is a kind of highlighting. The `Constant` should differ drom normal variables by their code style since almost every language uses all-upper-case for constants.
The `Special` group is a bit "special": I've searched many documentations, but was not able to really find which element of a language is defined as special. Could you post a code example so I can test the highlighting?

**Comment by mkalinski** [comment]
I don't think there's one definition of `Special`. It seems to me that most syntax files use this group for important elements that are specific to the language and do not easily fall under other groups.

Awk probably uses `Special` for too many things (including all operators and commas) but it's mostly used for special variable names and elements of regular expressions.

```awk
BEGIN {
  FS = "\t"
  some_var = 3
}

/A[[:space:]]B+\$/ {
  print $1
}
```

INI files use `Special` for section headings.

```
[foo]
bar = baz
```

Lisp uses it for quoted expressions.

```lisp
(format t "~a" '(1 2 3))
```

Also, for syntaxes not included in vim by default (at least last time I checked): SWIG and Jinja both use `Special` like awk, for predefined variables that are not keywords, but have some built-in functionality.

And those are the ones I encountered so far since I'm trying out Nord.

I also wouldn't agree that `Identifier` and `Constant` should be left without highlighting because everything else is highlighted. Most of "normal" text in any program is not highlighted by default (without using some tagging or IDE plugins, at least), so if a syntax file defines highlighting for some static elements deemed as `Identifier` or `Constant` it usually has a reason to. For example, Lua uses `Constant` for `true`, `false` and `nil`, and Java uses it for `null`.

**Comment by arcticicestudio** [comment]
I have to admit that I must have been a little bit "brain-afk" when I implemented the `Constant` definition 😱 
I'm mainly a Java- and javaScript developer and I use IntelliJ IDEA for almost everything, next to Atom as my normal default UI editor. IntelliJ detects a constant dynamically because it is a IDE, but Vim and the language syntax plugin of course can only define pattern so I confused a `Constant` with a user-defined readonly variable 😆 

You're totally right that some languages define elements like `true`, `false` `nil`/`null` as constants and these should be colored for sure. I'll change it to use `nord8` so they're colored as a kind of reserved keyword.

For the `Special` definition I'm still not sure if it should have a final color. I checked your code examples and the elements are using the `Special` group as a fallback color because the actual group they're assigned to is not defined in Nord.
This can easily be fixed by adding style support for these languages to Nord.

**awk**

| Element | Group |
| --- | --- |
| `BEGIN` | `awkPattern` |
| `FS` | `awkVariables` |
| `=` | `awkOperator` |
| `\t` | `awkSpecialCharacter` |
| `+\$` | `awkSearch`, `awkRegExp`, `awkSpecialCharacter` |
| `$1`  | `awkFieldVars` |

**INI**

| Element | Group |
| --- | --- |
| `[foo]` | `dosiniHeader` |

**Lisp**

| Element | Group |
| --- | --- |
| `(1 2 3)` | `lispAtomList` |

I have to agree for LispFor Lisp that both braces are colored by using the `Special` group, only the numbers inside are assigned to `lispAtomList`. In my option a bad syntax implementation and I don't know why it is not colored by using the base group `Delimiter` 😕 

Since Nord is designed to provide optimized styles to achieve a consistent and uniform coloring across languages I try to add all popular languages and optimize the syntax to be consistent with other languages instead of only defining the base groups which would lead to different results for example a class in Java and a class in other languages like javaScript or Python.

You can create a issue per language you'd like to see being included and maybe describe which elements should be optimized.

**Comment by arcticicestudio** [comment]
I'll create single issues for each of the langauges mentioned above and implement full highlighting support next weekend.

**Comment by arcticicestudio** [comment]
The problem with the `Special` group is that many syntax highlighting plugin creator are like "this language element doen't fit in any of the specifi groups so I just put it into Special".
If I'd colorize the `Special` group now with for example `nord9` some languages would have blue braces, some would have almost every word colored (which makes highlighting useless again) and other languages for debug purposes.

That's why I'll go with the more complex mehod by implementing styles for every plugin/language specific group, but this keeps the theme style consitent and avoids unintentional colorized elements.

**Comment by arcticicestudio** [comment]
I've implemented support for all three languages mentioned above in the issues references above this comment. All groups which are using `Special` as fallback are now mapped to a matching group.
Please let me know if you find other languages that should have better coloring support or would like to suggest improvements and feel free to open new issues per language. 

<p align="center"><strong>AWK</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/22405988/b902f896-e64a-11e6-9110-bd21a01eedaf.png"/><br><strong>Lisp</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/22405991/c8cad49c-e64a-11e6-80a8-db9d87d23115.png"/><br><strong>(DOS) INI</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/22405995/d7e00a60-e64a-11e6-86b3-13c3b795503f.png"/></p>
