### ISSUE TITLE
How to disable bold fonts?

### ISSUE THREAD

**Issue by tobydeh** [arcticicestudio/nord-vim#143]
How can i disable bold fonts for all filetypes?

**Comment by arcticicestudio** [comment]
Hi @tobydeh :wave:, thanks for your contribution :+1: 

There is currently only [support to configure italics][cit], but no configuration for bold yet. Adding support to allow users to enable/disable bold styles requires to implement this feature.

I've added it to the backlog, but feel free to implement it (maybe take a look at the implementation of the _italic_ config) if you like to, otherwise I (or someone else) will implement it as soon as there it time for it.

[cit]: https://github.com/arcticicestudio/nord-vim#italic-support

**Comment by tobydeh** [comment]
Sure, I’ll give it a go

**Comment by arcticicestudio** [comment]
@tobydeh The theme config has been implemented and released in [version 0.12.0](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.12.0).
