### ISSUE TITLE
Images in README.md broken

### ISSUE THREAD

**Issue by ma2rten** [arcticicestudio/nord-vim#144]

**Comment by arcticicestudio** [comment]
Hi @ma2rten :wave:, thanks for your contribution :+1:

I guess you're referring to the banners to the various port projects in the “**Getting Started** → **Installation**“ section. This is a known problem since the image files are stored in the [Nord repository itself][na] and have been moved or renamed, but this will be fixed as soon as the [documentation and assets transition][n#112] to [Nord Docs][nd#132] has been completed.
I'll leave this issue open as a reference when the documentation transition for this project's docs have also been completed.

[na]: https://github.com/arcticicestudio/nord/tree/develop/assets
[n#112]: https://github.com/arcticicestudio/nord/issues/112
[nd#132]: https://github.com/arcticicestudio/nord-docs/issues/132
