### ISSUE TITLE
viml  incorrect highlight when comment end with : and start with capital letter

### ISSUE THREAD

**Issue by maple-leaf** [arcticicestudio/nord-vim#147]
`nvim test.vim` and enter

```viml
" Test:
```

`Test:` being highlighted incorrectly.

![image](https://user-images.githubusercontent.com/3980995/55456431-9b3abd80-5619-11e9-8f03-79053352cafa.png)

**Comment by arcticicestudio** [comment]
Hi @maple-leaf :wave: 

I've tried to reproduce the problem using your use case and some other, but it works fine from my side.
Are you able to reproduce this behaviour? If yes I'd need to know the version of Neovim as well as the name and version of the terminal you're running.

Could you also please try to reproduce the problem using a clean (default) config that only loads the Nord theme? This ensures there's no other config or plugin that might cause this behaviour.

**Comment by maple-leaf** [comment]
neovim version: NVIM v0.4.0-430-g8698830cb (personal build from neovim source)

minimal config:
```viml
if empty($XDG_DATA_HOME)
    let $XDG_DATA_HOME = $HOME . '/.config'
endif

let mapleader = "\<Space>"

source $XDG_DATA_HOME/nvim/helper.vim
source $XDG_DATA_HOME/nvim/setting.vim

function! s:checkPlug()
	let vimplug_exists=expand('~/.config/nvim/autoload/plug.vim')

	if !filereadable(vimplug_exists)
	  if !executable("curl")
	    echoerr "You have to install curl or first install vim-plug yourself!"
	    execute "q!"
	  endif
	  echo "Installing Vim-Plug..."
	  echo ""
	  silent !\curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	  let g:not_finish_vimplug = "yes"

	  autocmd VimEnter * PlugInstall
	endif
endfunction

call s:checkPlug()

" Required:
call plug#begin(expand('~/.config/nvim/plugged'))

Plug 'arcticicestudio/nord-vim'

call plug#end()

```

screenshot of minimal config:
![image](https://user-images.githubusercontent.com/3980995/56106148-55afb600-5f72-11e9-9a8c-13d719cced13.png)

**Comment by arcticicestudio** [comment]
Oh, I thought you meant the grayish block on the colon, but you're referring to the color of the word and the gray block is actually your cursor 😆 
The word is highlighted because it uses the `vimCommentTitle` theme key that is defined by Vim's syntax definition and not the Nord theme. It will always match if a comment starts with one word without a dpace character followed by a colon.
There are actually more "special" comment elements like TODO keywords.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/56113441-2f801b00-5f5e-11e9-9e20-e3dca2e9dd70.png" /></p>

So this works as expected and won't change, but if you don't like this style you can customize it by overriding this theme rule. Add this snippet to your Vim config to apply the style **only for the Nord** theme:

```viml
augroup nord-theme-overrides
  autocmd!
  " Use Nord's default comment colors for comment titles in Vim files.
  autocmd ColorScheme nord highlight vimCommentTitle ctermfg=8 guifg=#616E88
augroup end
```
