### ISSUE TITLE
Color definitions should be using :highlight default

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#15]
Currently, nord-vim uses the bare `:hi` command to set up highlight colors, but it should be using `:hi def`.

From Vim documentation: https://vimhelp.appspot.com/syntax.txt.html#%3Ahighlight-default.

This will make it easier for users to customize coloring.

Right now, any custom modifications must be placed after the `:color nord` command in the `.vimrc` file and calling `:color nord` again erases those modifications.

**Comment by arcticicestudio** [comment]
Yes, this should definitely be changed to now override custom definitions.
Thanks, I'll implement it next weekend :smile:

**Comment by arcticicestudio** [comment]
I have to revoke my previous statement because I've misunderstood your problem.
If you'd like to override specific syntax highlighting you can make use of vim's `autocmd`.

Example on how to override Nord's CSS class name color with red:  
```vim
autocmd ColorScheme * highlight cssClassName ctermfg=red
```

If you'd like to override multiple definitions you can create a `augroup` for it:
```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme * highlight cssClassName ctermfg=blue
  autocmd ColorScheme * highlight cssPseudoClass ctermfg=yellow
augroup END
```

Note that these changes will always override **every** color theme even if you set `:colorscheme nord` or any other colorscheme!

**Comment by mkalinski** [comment]
You're right, this can be done using autocommands, I forgot about them. Still, is there any particular reason you don't want to use the `default` option? Most of the colorschemes I've seen do it.

(Also, technically you could use `autocmd ColorScheme nord ...` instead of `if`s, since in this case the pattern is matched against the colorscheme name)

**Comment by arcticicestudio** [comment]
The `autocmd ColorScheme nord` command is indeed the best and cleanest solution for this 👍 

I've read some StackOverflow threads and old Vim mailing lists and I think I've understand the way the `default` keyword works.
The link to the Vim documentation you posted above describes that the `default` keyword is especially used for `syntax` files:
> Using [default] is especially useful to overrule the highlighting of a
specific [syntax](https://vimhelp.appspot.com/syntax.txt.html#syntax) file [...]

The flow should be the following:
A syntax file links the groups it contains to the base groups with the `default` keyword added to let Vim know that this should be the default group for this syntax to colorize the new filetype **except**  if a colorscheme sets them differently.
The colorscheme should not set a group of a syntax file, which are both exists to fulfill different purposes, but **override** the default value of it.

I've checked almost over 20 of the most popular and advanced themes like
  - solarized
  - gruvbox
  - molokai
  - ...
and none of them uses the `default` / `def` keyword.
I think the reason for it is clear:
As soon as a colorscheme uses the `default` keyword its rules will be overriden by the syntax file because it takes precedence.
I've tested it with Nord by adding the `def` shorthand and the syntax highlighting broke since it has been overriden by the rules of the syntax file.

![ghi-15-scrot-default-override-test](https://cloud.githubusercontent.com/assets/7836623/22442404/888fa7f8-e73b-11e6-97fe-ddc9f60e4cd6.png)

As you can see on the screenshot the only intact colors are the ones from the lightline plugin since there is of course no syntax file for it.

In summary the `default` keyword is used for a different feature of Vim, but colorschemes should not use it.

About your test with the `autocmd`:
It works fine for me with the `highlight` command without the `!`, but you have to make sure that the `augroup` is placed **after** the `colorscheme nord` line!

Finally I just want to let you know that I'm happy for every improvement suggestion, but in this case I don't see any improvement for the theme. If users want to override specific groups of the theme they can create a `augroup` with `autocmd ColorScheme nord` commands which can be nicely done for other colorschemes too, maybe I'll add a small guide to the wiki as help resource.

Anyway, it would be nice to hear why you'd like to add the `default` keyword to Nord even if there is a clean and simple solution to define overrides for colorschemes?

**Comment by mkalinski** [comment]
Okay, I can see I've goofed in this case.

The reason I proposed using `default` is for ease of overriding. I've dabbled in overriding some colors in my configuration in the past, and with the plugins using `default` it just worked: put `highlight ...` somewhere where it was loaded and that was it. I thought it would be good if users could avoid needing to think about whether `!` is needed or where exactly the autocommands should be put.

I've also seen plugins use `hi def` outside of syntax files, which is why I though it's something you're just supposed to do when writing a plugin, but I failed to noticed that in all cases they were defining new syntax groups, while colorschemes always just override existing ones. Your test proves I was looking at this the wrong way.

You can consider this issue closed.
