### ISSUE TITLE
After a recent update my airline bar has disappeared on the inactive splits

### ISSUE THREAD

**Issue by rostero1** [arcticicestudio/nord-vim#156]
I recently updated to the latest nord-vim release and the inactive splits no longer show a greyed out airline bar, but shows no bar at all.  This makes it hard to see see where one split ends when in a horizontal split.

Is there a config I'm missing?

Really amazing job on this theme.

**Comment by arcticicestudio** [comment]
Hi @rostero1 :wave:, nice to see you like the theme :smile: 
I am not really sure if I get you right because you're referring to [airline][], but your description sounds more like the change that was made in [v0.11.0][] (scroll down to „Theme config for bolder vertical split line“) merged in #153. If you meant that, then you can add `let g:nord_bold_vertical_split_line = 1` to your config to use the previous split line design again.

[airline]: https://github.com/vim-airline/vim-airline
[v0.11.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.11.0

**Comment by arcticicestudio** [comment]
@rostero1 Is the theme configuration what you were looking for? If so, please close this issue.

**Comment by arcticicestudio** [comment]
I guess the problem can be seen as resolved since it is related to the new theme configuration so I close this ticket for now. If you're still affected by the problem or think the issue it not solved yet please reply or reopen this issue, thanks :+1:
