### ISSUE TITLE
Incorrect color contrast on vim with st

### ISSUE THREAD

**Issue by loustak** [arcticicestudio/nord-vim#166]
I'm using vim 8.1 (with +termguicolors) inside st under dwm. I applied the [nord theme to st](https://github.com/arcticicestudio/nord/issues/89). I installed nord trough Plug as recommended.

But for some reason some colors are incorrect inside vim... For instance as you can see on the screenshots line numbers and comments color are to close to the background color.

More, there is no visual selection color at all. Everything else looks ok trough...

![1561487256](https://user-images.githubusercontent.com/11078371/60123676-50e45b00-9788-11e9-9846-81fcb756e346.png)

**Comment by arcticicestudio** [comment]
Hi @loustak :wave:, please note that the linked st theme **is not an official theme** but a contribution of a Nord user. I've not checked if the used colors are matching Nord's styles for syntax highlighting so your problem might be related to this.
I've quickly checked the proposed theme and the [adjustment of Nord's comment color][nord-cb-poll] is not included. This explains why comments and the line numbers using a darker color ( `nord3`) instead of the new `#616e88` value ( `nord3` brightness increased by 10%).

Also another problem might be that you Vim and terminal is not configured to use _true colors_. Can you please try to add the following config to your `.vimrc` and check if the problem still occurs:

```viml
if (has("termguicolors"))
  set termguicolors
endif
```

Also please make sure you're running **at least Nord Vim [v0.10.0][] or higher**, otherwise the new comment color is also not supported.

[nord-cb-poll]: https://github.com/arcticicestudio/nord/issues/94
[v0.10.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.10.0

**Comment by loustak** [comment]
Thanks for the answer @arcticicestudio. I tried changing the color inside my st configuration to the new nord3 color. No changes.

I checked my vim and tried `set termguicolors` it make all the text goes white:
![1561628833](https://user-images.githubusercontent.com/11078371/60256162-539e9780-98d1-11e9-9543-985bc85b717d.png)

I checked the nord vim version inside nord.vim installed by plug, and I'm using **v0.12.0**:
```vim
let s:nord_vim_version="0.12.0"
```

**Comment by loustak** [comment]
I found a solution: https://github.com/vim/vim/issues/993#issuecomment-255651605

Adding the following lines to my `.vimrc` solved all my colors problems:
```vim
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

**Comment by DictumMortuum** [comment]
Did the same thing, however I still can't get the current line highlight to work.
Maybe that requires a different sequence?

**Comment by loustak** [comment]
@DictumMortuum you are right. I didn't noticed it first but I have the exact same issue. So I reopen it.

**Comment by arcticicestudio** [comment]
Has someone found a solution to also enable highlight support for the current cursor line?
I haven't installed and configured _st_ so having some help here would be nice to resolve this ticket.

**Comment by DictumMortuum** [comment]
I'd be happy to help, but I'm not sure what I should do - do you want me to try anything?

**Comment by arcticicestudio** [comment]
Does it work if you're disabling italic font rendering in both _st_ and the [specific Nord theme configuration][c]? Might be possible that there are conflicts with the terminal sequences.

[c]: https://www.nordtheme.com/docs/ports/vim/configuration#italic-style

**Comment by cyrilaugier** [comment]
Hi !

St + vim works perfectly for me with this configuration. :wink:

St + Vim
![st_nord](https://user-images.githubusercontent.com/48598522/61871959-6f05be00-aee2-11e9-8116-861fe8d036e0.png)

St + Tmux + Vim
![st_nord_tmux](https://user-images.githubusercontent.com/48598522/61871958-6f05be00-aee2-11e9-8722-e7079784e86b.png)


``` vim
" ~/.vimrc

if exists('+termguicolors') && ($TERM == "st-256color" || $TERM == "tmux-256color")
	let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
	let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
	set termguicolors
endif

let g:nord_italic = 1
let g:nord_italic_comments = 1
let g:nord_underline = 1
let g:nord_uniform_status_lines = 1
let g:nord_uniform_diff_background = 1
let g:nord_cursor_line_number_background = 1
colorscheme nord
```


``` tmux
# ~/.tmux.conf

# $TERM, fix colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
```

Source : https://github.com/tmux/tmux/issues/1246#issue-292083184

**Comment by loustak** [comment]
For my case, I'm not running vim inside tmux.
@cyrilaugier can you provide the versions of st, vim and nord please? Because I have the same setup without tmux and I don't get the current line highlighted.
![1564073697](https://user-images.githubusercontent.com/11078371/61893135-a76ec180-af0d-11e9-9058-cad036e84536.png)

**Comment by arcticicestudio** [comment]
@cyrilaugier Thanks, this helps a lot to encircle the root cause :+1: 

@loustak I guess I've also misunderstood your actual problem: I thought you're having wrong styles for the current line highlighting (like e.g. too dark or totally wrong color), but I guess this is also just a Vim setup problem on your side.
Have you enabled Vim's `cursorline` option? Otherwise the current line won't be highlighted at all :smile: 
You can add `set cursorline` to your `vimrc` to enable it by default or run the command from within Vim.

**Comment by loustak** [comment]
Okay, I'm stupid, I just forgot to add the `cursorline` option...

The issue seems close now.

**Comment by arcticicestudio** [comment]
@loustak Not stupid, human. I could tell you a lot of private or job-related development/coding situations   where I was like "wow, the fix was a one-liner" after spending hours with debugging :upside_down_face: 
Glad to see it works for your now.

@DictumMortuum Could you please also check if you're just missing the `cursorline` option? Otherwise we need to check other settings that might conflict with the theme.

**Comment by DictumMortuum** [comment]
Currently on vacation, but I believe that I don't have the cursor line
option enabled. Will check and update you as soon as possible !

**Comment by DictumMortuum** [comment]
Confirmed, I'd forgot to set the cursorline option. I think that we can close!
