### ISSUE TITLE
Vim 8 terminal colors

### ISSUE THREAD

**Issue by bdielman** [arcticicestudio/nord-vim#172]
I have my prompt (zsh and iTerm) using Nord for iTerm. I have the colors setup like so: blue for the path, red for Ruby version, green for Node version, and yellow for git info:

<img width="947" alt="Screen Shot 2019-08-26 at 1 08 23 PM" src="https://user-images.githubusercontent.com/94547/63709457-ecd02880-c804-11e9-9773-b68c489234bc.png">

When in Vim (also using Nord of course) and I use the integrated terminal, the yellow for the git info shows up as a dark orange instead:

<img width="949" alt="Screen Shot 2019-08-26 at 1 08 09 PM" src="https://user-images.githubusercontent.com/94547/63709495-06717000-c805-11e9-87bc-8d57321085e6.png">

Any thoughts as to why or how I could fix this in my setup?

**Comment by arcticicestudio** [comment]
Hi @bdielman :wave:, thanks for your contribution :+1:
Sorry for the delay, unfortunately my free time to work on Nord is limited.

Have you tried to reproduce the problem using a clean/empty Vim configuration file that only sets the Nord `colorscheme`?
It might be possible that you also need to set the `termguicolors` variable to enable _true color_ support in Vim.

```viml
if (has("termguicolors"))
  set termguicolors
endif
```

Also please make sure to use the latest plugin version or at least [v0.10.0][] since this version introduced support for Vim's integrated terminal mode.

[0.10.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.10.0

**Comment by bdielman** [comment]
Your second suggestion did the trick: set `termguicolors`. Thanks!
