### ISSUE TITLE
Not working with vim-indent-guides

### ISSUE THREAD

**Issue by mitinarseny** [arcticicestudio/nord-vim#186]
not working with [vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides)
I guess it is because of [theese](https://github.com/arcticicestudio/nord-vim/blob/aa1470403a300a7d5088057d970c13d4388eb13e/colors/nord.vim#L176) lines

**Comment by arcticicestudio** [comment]
Hi @mitinarseny :wave:, thanks for your contribution :+1:

The plugin uses two custom highlight groups [`IndentGuidesOdd` and `IndentGuidesEven`][g] to style the indent lines. The [`indent_guides#highlight_colors()` function][f] supports both GUI and terminal mode, but uses the same groups.
In order to make it work with Nord both groups should be added to the theme.
I've added it to the backlog, but feel free to submit a PR if you like.

[g]: https://github.com/nathanaelkane/vim-indent-guides/blob/master/autoload/indent_guides.vim#L144-L145
[f]: https://github.com/nathanaelkane/vim-indent-guides/blob/master/autoload/indent_guides.vim#L94

**Comment by dagolinuxoid** [comment]
@mitinarseny  Have you tried https://github.com/Yggdroot/indentLine as an alternative? It looks great especially with custom indent char as  `let g:indentLine_char = ‘⎸'` for example.
