### ISSUE TITLE
Airline Theme no longer working

### ISSUE THREAD

**Issue by heliostatic** [arcticicestudio/nord-vim#187]
Since updating to https://github.com/arcticicestudio/nord-vim/commit/73b3d340a735a2b6915f62a8904d6521251375cd the Airline theme no longer applies successfully on Neovim with vim-airline https://github.com/vim-airline/vim-airline/commit/b93492b40b068d4bb3020c123295061aaba7c846

**Comment by arcticicestudio** [comment]
Hi @heliostatic :wave:, thanks for your contribution :+1:

I've tried to reproduce the problem, but it works fine with the [current `develop` branch][b], when explicitly checking out the 73b3d34 commit as well as the [latest release version 0.13.0][v] that includes the change. I've used this minimal test `vimrc`:

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'vim-airline/vim-airline'
Plug 'arcticicestudio/nord-vim'
call plug#end()

" Works with both enabled and disabled option.
let g:nord_uniform_status_lines = 0

syntax enable
colorscheme nord
```

Could you please provide a minimal `vimrc` and a small step-list how to reproduce the problem on your side? Also please post a screenshot of what's not working any more (or the exact error message) as well as more information about your setup like the Neovim version and the way plugins are installed and loaded.

[b]: https://github.com/arcticicestudio/nord-vim/tree/aa1470403a300a7d5088057d970c13d4388eb13e
[v]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.13.0

**Comment by heliostatic** [comment]
I found the culprit -- I was also loading https://github.com/flazz/vim-colorschemes and the `nord` theme in there was causing the issue. I'm not sure how to specify loading the correct `nord`, but in the short term the problem is solved. Thank you so much for the minimal `vimrc` for testing.

**Comment by arcticicestudio** [comment]
Nice to see you found the root cause :smile: 
„Collections” and „theme bundles” like these are always a problem when it comes to code maintenance since themes are copied once but never kept up-to-date with their upstreams. In general I'd recommend to avoid them and instead explicitly install plugins you really like to use, otherwise you'll also add like e.g. 200 files to your setup while only using one of them.
I guess the problem with the plugin is the fact that the [`nord_uniform_status_lines` variable][ref] is not defined in the theme at all (last update was _23 Aug 2017_ :astonished:)

Anyway, glad to see it works for you now.

[ref]: https://github.com/arcticicestudio/nord-vim/blob/7fd74817c3be4158a52f76f6f6d8076c8c9d46a8/colors/nord.vim#L109-L111
