### ISSUE TITLE
Want to lighten the comment color

### ISSUE THREAD

**Issue by Jzarecta** [arcticicestudio/nord-vim#196]
I am studying the colors/nord.vim pallet because I would like to lighten the comments a bit. With the terminal opacity set to 80, comments tend to blend too much with the background. So I would like to have a bit litten comments. I see there is a variable called comment_brightness but not sure where exactly to activate it. Also this is for vim in terminal, not on GUI.

**Comment by arcticicestudio** [comment]
Hi @Jzarecta 👋
The `nord_comment_brightness` plugin configuration variable is deprecated since plugin version [0.10.0][] and is not loaded anymore because the default comment color was changed according to https://github.com/arcticicestudio/nord/issues/94.

To customize the theme to fit your needs, check out [Nord Vim's official “Customization“ port project documentation][d].

The style key for comments is `Comment`, so you can change it to any other value like e.g. `nord6`:

```vim
augroup nord-theme-overrides
  autocmd!
  " Use 'nord6' as foreground color for all comments.
  autocmd ColorScheme nord highlight Comment ctermfg=15 guifg=#ECEFF4
augroup END
```

[0.10.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.10.0
[d]: https://www.nordtheme.com/docs/ports/vim/customization

**Comment by dagolinuxoid** [comment]
@Jzarecta  btw be sure yours  `set termguicolors` works properly, actually setting t_8f and other stuff as needed consumed a lot of time
