### ISSUE TITLE
Italics in a React project?

### ISSUE THREAD

**Issue by casperstorm** [arcticicestudio/nord-vim#197]
I tried to follow https://github.com/arcticicestudio/nord-vim/issues/88 however the [link](https://github.com/arcticicestudio/nord-vim#italic-comments) is dead.

I have italics in a markdown file, but im trying to get it to work in a React project. Any help would be nice.
I have this in my `init.vim`

```vim
let g:one_allow_italics = 1
hi htmlArg gui=italic
hi htmlArg cterm=italic
hi Comment gui=italic
hi Comment cterm=italic
hi Type    gui=italic
hi Type    cterm=italic
let g:nord_italic = 1
colorscheme nord
```

**Comment by casperstorm** [comment]
This was me, the ordering here was wrong. I have it working now. Thanks for this awesome theme.

**Comment by arcticicestudio** [comment]
More information about theme customization can also be found in the [official Nor Vim documentations][d]. Maybe you like to make use of a `augroup` in order to apply these changes only for the Nord theme instead of globally for all themes.

[d]: https://www.nordtheme.com/docs/ports/vim/customization

**Comment by casperstorm** [comment]
Oh this is what I’ve missed! Thanks a lot.
