### ISSUE TITLE
Choosing color scheme (e.g. nord6)

### ISSUE THREAD

**Issue by ohjang121** [arcticicestudio/nord-vim#209]
Dear arcticicestudio,

I am very new to vim setups, and `nord` was by far my favorite for its high quality aesthetics - thank you so much for building this! 

That said, I would love to explore different color schemes that it provides (e.g. `nord6` from [this color scheme](https://www.nordtheme.com/docs/colors-and-palettes)). The following screenshot is my `.vimrc` for `nord` plugin:

<img width="713" alt="Screen Shot 2020-06-15 at 3 11 45 AM" src="https://user-images.githubusercontent.com/49255961/84628063-fe7add80-aeb5-11ea-8421-bd1b34b7cb97.png">

I reverted it back to `colorscheme nord` for the time being to avoid the error, but I would love to know the following:
1. How to implement different color schemes for vim (I assume I have to configure them before I define `colorscheme nord`, but could not find a good example on this anywhere.)
2. How to set the color scheme for terminal to match the vim color scheme

I spent more than an hour trying to search and google this, so please bear with me if this is a trivial issue :( I would very much appreciate help here - let me know if I need to provide further info!

**Comment by arcticicestudio** [comment]
Hi @ohjang121, looks like you're confusing the structure of Nord. It consists of 16 colors in total that are kind of categorized into four palettes, but this builds a single theme and not different themes.
The error you're facing is that you're trying to use a single palette as theme while the actual name is just `nord` which should work fine.
Please try again with `colorscheme nord` and maybe also check out the [official Nord Vim installation documentation][docs] for more details.

[docs]: https://www.nordtheme.com/docs/ports/vim/installation

**Comment by ohjang121** [comment]
Hey @arcticicestudio ,

Thank you for the clarification and such a quick response! I understand that `colorscheme nord` is the correct set up (which I mentioned I reverted back to it in the post), but I am having trouble how to select a theme or palette of my choice in the selection of themes provided. That was more of the question I wanted to answer, if there is a way to configure it before defining `colorscheme nord` in my vimrc.

**Comment by arcticicestudio** [comment]
> [...] to select a theme or palette of my choice in the selection of themes provided.

That is the point: There are not other themes 😄 
Nord is a single theme like any other Vim theme (e.g. _Solarized_ or _Monokai_) with the difference that all colors are internally categorized into four different palettes to make their purpose and meaning more clear. Anyway, in the end Nord is just one theme with the standard amount of 16 colors for the terminal ANSI colors.
There are [custom theme configurations][d] that allow to tweak different aspects like e.g. the rendering of _italic_ and **bold** styles.
But using just one of the four color palettes is not the way this works. It would also be kind of impossible since e.g. the “snow storm“ palette only consists of a total of 4 colors so it would end up in “invisible“ text or UI elements because they'd “merge“ with other elements that use the same foreground/background color. 

[d]: https://www.nordtheme.com/docs/ports/vim/configuration

**Comment by ohjang121** [comment]
Ahhh that makes sense - thank you for the clarification!! I was having a hard time understanding that aspect... thank you.

**Comment by arcticicestudio** [comment]
You're welcome 😄
