### ISSUE TITLE
remove tilde endofbuffer 

### ISSUE THREAD

**Issue by cyh0** [arcticicestudio/nord-vim#212]
could you remove the tilde end of buffer, I think it looks uncomfortable. thanks.

**Comment by arcticicestudio** [comment]
Hi @cyh0 :wave:, thanks for your contribution :+1:

I guess you're referring to these characters?

<p align="center">
<img src="https://user-images.githubusercontent.com/7836623/86437039-e56e8b00-bd03-11ea-87e2-9905c6792729.png" width="160px"></p>

Nord currently uses `nord1` to highlight the `EndOfBuffer` group which is responsible for these characters. Making them invisible by using the same color like the background would mean other users who are used to these characters would need to customize their theme configuration to make them visible again. A theme should not mess with Vim defaults like this since it causes more confusion than it helps.

But this is not a blocker for you to get rid of them. If you're not in agreement with all of Nord Vim's design decisions you can [simply override every theme style you like][d]. In this case adding the following to your Vim configuration should make these characters not visible anymore:

```vim
augroup nord-theme-overrides
  autocmd!
  " Use same color for EOB tilde characters like the theme background to make them not visible anymore.
  autocmd ColorScheme nord highlight EndOfBuffer ctermfg=NONE guifg=NONE
augroup END
```

[d]: https://www.nordtheme.com/docs/ports/vim/customization

**Comment by cyh0** [comment]
ok, thanks.
