### ISSUE TITLE
Comment Color Brightness Doesn't Apply

### ISSUE THREAD

**Issue by EvasiveUmbrella** [arcticicestudio/nord-vim#222]
Using: `gnome-terminal` + `tmux` + `nvim`.
From https://github.com/arcticicestudio/nord/issues/94, it was seen that `nord3` was updated from `#4C566A` to `#616E88`.
In my `v0.15.0` `~/.vim/plugged/nord-vim/colors` file, these lines are present:
```
let s:nord3_gui = "#4C566A"
let s:nord3_gui_bright = "#616E88"
```
However, the comment colors are still the darker version:
![image](https://user-images.githubusercontent.com/24905054/90301750-b48b8500-de6f-11ea-87e0-9b06ca147d10.png)
I am certain that the aforementioned file is the one controlling the colors, as moving it resets neovim to the default color scheme.
I have tried copying the file found here https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim into my `colors` file, but there was no change. Nor does changing the values of `s:nord3_gui` or `s:nord3_gui_bright` to colors like `#FF0000` do anything.
How can I get the brighter comment color? If editing the file doesn't work, can I change the setting from `.vimrc` instead?

**Comment by arcticicestudio** [comment]
Hi @EvasiveUmbrella :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered. This is because, like described in arcticicestudio/nord#94, the actual color palette hasn't changed but only ports that are targeted to applications with syntax highlighting. The `*_term` attributes make use of the colors that are provided by the terminal color scheme [which is Nord GNOME Terminal in your case][ref]. The `*_gui` variables on the other side are used when Vim runs in GUI mode and when the `termguicolors` is set and the terminal supports “true colors“ (24bit).

Please try to either use the example configuration or set the `termguicolors` setting in your current configuration.

[ref]: https://github.com/arcticicestudio/nord-gnome-terminal/blob/5b9c057/src/nord.sh#L32
[vim-plug]: https://github.com/junegunn/vim-plug

**Comment by EvasiveUmbrella** [comment]
![image](https://user-images.githubusercontent.com/24905054/90822242-23e6f600-e302-11ea-83db-6510f30b55e4.png)
Perfect, thank you very much!
In hindsight, the `_gui` suffix should have been a clear indication of my error

**Comment by arcticicestudio** [comment]
Nice to see it works for you now 😄
