### ISSUE TITLE
Comments are too dark

### ISSUE THREAD

**Issue by pr3c0g** [arcticicestudio/nord-vim#227]
Hi all, love this theme!

It looks like the comments are too dark.
Also, looking at your screenshots, your comments seem to be brighter than mine.

Comparission:
My NERDTree: 
![image](https://user-images.githubusercontent.com/11090205/95996922-20b44600-0e2b-11eb-9458-7bc4ef3b80a1.png)
Your NERDTree:
![image](https://user-images.githubusercontent.com/11090205/95996972-2f026200-0e2b-11eb-89d7-800bd7f6d1c6.png)

I changed the line `let s:nord3_term` on file `nord.vim` to other numbers but I can't get a brighter grey, only other colors.
What do these numbers correspond.

I'm running OSX, NVIM v0.4.4, and I have nord-vim installed via Vundle and updated (going to the folder shows develop branch, commit ea7ff9c343392ec6dfac4e9ec3fe0c45afb92a40)

Thank your for the help and sorry if I misinterpreted something!

**Comment by aduros** [comment]
+1, comments seem pretty hard to read out of the box.

You can change it from black to darkgray by putting this in your config (after setting the colorscheme): `highlight Comment ctermfg=darkgray`

You might need to add more highlight groups if NERDTree uses something other than Comment.

I like to also make comments italic by adding `cterm=italic` to that line.

**Comment by arcticicestudio** [comment]
Hi @pr3c0g :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because, like described in arcticicestudio/nord#94, the actual color palette hasn't changed but only ports that are targeted to applications with syntax highlighting. The `*_term` attributes make use of the colors that are provided by the terminal color scheme which might be [iTerm2][ref-iterm] or [Terminal.app][ref-term.app] in your case . The `*_gui` variables on the other side are used when Vim runs in GUI mode and when the `termguicolors` is set and the terminal supports “true colors“ (24bit).

@pr3c0g Could you please try to either use the example configuration or set the `termguicolors` setting in your current configuration and check whether the brightened comment color is then displayed correctly?

[ref-term.app]: https://github.com/arcticicestudio/nord-terminal-app/blob/master/src/xml/Nord.terminal#L23-L31
[ref-iterm]: https://github.com/arcticicestudio/nord-iterm2/blob/master/src/xml/Nord.itermcolors#L187-L199
[vim-plug]: https://github.com/junegunn/vim-plug

**Comment by pr3c0g** [comment]
Thank you for your very detailed response!

Setting `termguicolors` makes the colors like they should be, thank you very much for that :)

**Comment by arcticicestudio** [comment]
@pr3c0g Nice to see it works for you now 👍🏼 

@aduros If you also encountered the problem, but the described solution above doesn't works for you please open a new issue.
