### ISSUE TITLE
The colours don’t appear as advertised 

### ISSUE THREAD

**Issue by Aron-R** [arcticicestudio/nord-vim#238]
Hello there,
I recently decided to switch to NeoVim and I am trying to set it up with the themes and everything 
I really liked the Nord theme when I came across it as I was browsing themes on google 
And so I tried to install it and apply it
And I did but... not quite 
I get it like this 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/55871316/102320054-cd34b480-3fa1-11eb-9483-c2596d482d65.png">

I tried searching the issue online, and I found [This article](https://github.com/arcticicestudio/nord-vim/issues/111#issue-305243334 ) but it wasn’t as much help as my color codes were completely off  
I also tried deleting it and installing it again but it didn’t work

I was hoping I’d get some help as to setting up the Nord theme as advertised. I don’t know if this is an issue of lack of knowledge on my part (I’m new to vim so please bear with me) or if it’s some other issue 

Nvim version: 0.4.4
Mac OS: Big sur version 11.0.1

Thank you for taking the time to read this

**Comment by arcticicestudio** [comment]
Hi @MachineGunMaverick 👋🏼

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```



As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because the [`*_term` attributes][gh-blob-term_attr] make use of the colors that are provided by the terminal color scheme which might be for example [iTerm2][iterm2] or [Terminal.app][term.app] in your case. The [`*_gui` variables][gh-blob-gui_attr] on the other side are used when Vim runs in GUI mode. So in order to run Vim in a terminal but use colors like in GUI mode the `termguicolors` variable must be set and your terminal emulator must support “true colors“ (24bit).

Unfortunately terminal colors are quite complex due to their long history, but modern terminal emulators should be all capable of rendering "True Colors". You should make sure to check out the great [“Terminal Colors“ gist][gist-tc] that provides many details about color rendering in terminal emulators, tracking of supported terminal emulator projects and answers to common confusions about terminal colors. The [“Colours in terminal“ gist][gist-cit] is also quite helpful to learn more about the actual rendering engines and standards used by these terminal emulators.
There are also a lot of blog posts like [this][bp1] and [this][bp2] one that help to handle different use case with various terminal emulators in combination with different CLI and TUI applications.

1. Please ensure you installed the corresponding Nord theme for your terminal emulator, e.g. [Nord iTerm2][iterm2] or [Nord Terminal.app][term.app].
1. CPlease try to either use the example configuration or set the `termguicolors` setting in your current configuration and check whether colors are then displayed correctly.

[term.app]: https://github.com/arcticicestudio/nord-terminal-app
[iterm2]: https://github.com/arcticicestudio/nord-iterm2
[vim-plug]: https://github.com/junegunn/vim-plug
[bp1]: https://sts10.github.io/2016/06/15/true-hex-colors-in-vim-with-iterm2.html
[bp2]: https://tomlankhorst.nl/iterm-tmux-vim-true-color
[gist-tc]: https://gist.github.com/XVilka/8346728
[gist-cit]: https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9
[gh-blob-term_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L37-L49
[gh-blob-gui_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L19-L35
