### ISSUE TITLE
incorrect color scheme

### ISSUE THREAD

**Issue by so0jong** [arcticicestudio/nord-vim#249]
hello!

I installed nord and port for terminal.app, and I'm having incorrect color. I followed install documentation also. 

<img width="888" alt="Screen Shot 2021-02-15 at 3 12 37 PM" src="https://user-images.githubusercontent.com/42879329/108001039-418ad480-6fa0-11eb-8f01-00acfe82be07.png">

Here's my .vimrc

```
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set hidden

set termguicolors
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim'
Plug 'lervag/vimtex'
Plug 'sirver/ultisnips'
Plug 'KeitaNakamura/tex-conceal.vim'
call plug#end()

" vimtex
let g:vimtex_quickfix_mode=0
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
set conceallevel=1
let g:tex_conceal='abdmg'

" UltiSnips
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'

" tex-conceal
set conceallevel=1
set spelllang=en_us
inoremap <C-l> <c-g>u<Esc>[s1z=']a<c-g>u

" nord
colorscheme nord
let g:nord_unifom_status_lines=1
let g:nord_bold_vertical_split_line=1
let g:nord_cursor_line_number_background=1
" let g:nord_uniform_diff_background=1
```

**Comment by arcticicestudio** [comment]
Hi @so0jong :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because the [`*_term` attributes][gh-blob-term_attr] make use of the colors that are provided by the terminal color scheme which might be for example [iTerm2][ref-iterm]. The [`*_gui` variables][gh-blob-gui_attr] on the other side are used when Vim runs in GUI mode. So in order to run Vim in a terminal but use colors like in GUI mode the `termguicolors` variable must be set and your terminal emulator must support “true colors“ (24bit).

Unfortunately terminal colors are quite complex due to their long history, but modern terminal emulators should be all capable of rendering "True Colors". You should make sure to check out the great [“Terminal Colors“ gist][gist-tc] that provides many details about color rendering in terminal emulators, tracking of supported terminal emulator projects and answers to common confusions about terminal colors. The [“Colours in terminal“ gist][gist-cit] is also quite helpful to learn more about the actual rendering engines and standards used by these terminal emulators.
There are also a lot of blog posts like [this][bp1] and [this][bp2] one that help to handle different use case with various terminal emulators in combination with different CLI and TUI applications.

Could you please try to use the example configuration and check whether colors are then displayed correctly?

[ref-iterm]: https://github.com/arcticicestudio/nord-iterm2/blob/b334a9b4/src/xml/Nord.itermcolors#L187-L199
[vim-plug]: https://github.com/junegunn/vim-plug
[bp1]: https://sts10.github.io/2016/06/15/true-hex-colors-in-vim-with-iterm2.html
[bp2]: https://tomlankhorst.nl/iterm-tmux-vim-true-color
[gist-tc]: https://gist.github.com/XVilka/8346728
[gist-cit]: https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9
[gh-blob-term_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L37-L49
[gh-blob-gui_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L19-L35
