### ISSUE TITLE
Selection won't change color in neovim on alacritty 

### ISSUE THREAD

**Issue by glyh** [arcticicestudio/nord-vim#250]
### screenshot

![2021-02-19_13-41](https://user-images.githubusercontent.com/12870742/108462814-3b566a00-72b8-11eb-9e32-5ecd333cbccb.png)

### vim-plug's snapshot output 
```
silent! let g:plugs['nord-vim'].commit = 'ea7ff9c343392ec6dfac4e9ec3fe0c45afb92a40'
```
### neovim version
```
:version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
-O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -
Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATE
D_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/
src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### minimal init.vim to reproduce the problem:

```vim
call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim' " colorscheme
call plug#end()
colorscheme nord
```

**Comment by arcticicestudio** [comment]
Hi @glyh :wave:

Thanks for the minimal reproduction configuration. Can you please add the following and test again?

```vim
set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
```

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because the [`*_term` attributes][8] make use of the colors that are provided by the terminal color scheme, e.g. [Alacritty][1] in your case. The [`*_gui` variables][9] on the other side are used when Vim runs in GUI mode. So in order to run Vim in a terminal but use colors like in GUI mode the `termguicolors` variable must be set and your terminal emulator must support “true colors“ (24bit). This could fix the comment color not being brightened (see arcticicestudio/nord#94 for details) and the missing selection color.

I also remember that Alacritty uses [custom _terminfo_ definitions][ti] which might be necessary to set up properly.

[1]: https://github.com/arcticicestudio/nord-alacritty
[2]: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo

**Comment by arcticicestudio** [comment]
@glyh Have you been able to solve the problem? If yes it would be nice if you could summarize your solution to help others who are facing the same problem.

**Comment by glyh** [comment]
Sorry for delay so long time, I've tested the code above and it fixes this problem. Thanks a lot!
