### ISSUE TITLE
Not all colors are applied properly - kitty terminal

### ISSUE THREAD

**Issue by IronSideSec** [arcticicestudio/nord-vim#254]
Hi! I am using kitty and manually applying colorscheme using Nord Xresources colors, but when applying vim nord not all colors are right - the most noticeable difference is the one comments are rendered with, and the selection. Attaching screenshot for reference. I tried applying alacritty colorscheme but it looked even worse in this combination.. Any way I can manually try to change this one color? Tried to switch it inside the nord.vim file but it never respected the changes.. 
![2021-03-27T16:32:18,319519951+01:00](https://user-images.githubusercontent.com/60072908/112726038-90227b80-8f1b-11eb-94b4-1cad092149dd.png)

**Comment by arcticicestudio** [comment]
Hi @IronSideSec :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [3][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because the [`*_term` attributes][8] make use of the colors that are provided by the terminal color scheme. The [`*_gui` variables][9] on the other side are used when Vim runs in GUI mode. So in order to run Vim in a terminal but use colors like in GUI mode the `termguicolors` variable must be set and your terminal emulator must support “true colors“ (24bit). This could fix the comment color not being brightened (see arcticicestudio/nord#94 for details) and the missing selection color.

It's also possible that you're using a terminal that doesn't work out-of-the-box with 24-bit colors so in order to use the `termguicolors` option some additional steps are required. For example, see https://github.com/arcticicestudio/nord-emacs/issues/59#issuecomment-503738384 which describes that the [kitty][10] terminal requires a extra [terminfo][11] file. What is the output when you run `echo $TERM`?
Maybe you'd also like to [check out the great Gist about colors in terminals][12], there are many information why colors are still sometimes a pain in terminals.

Unfortunately terminal colors are quite complex due to their long history, but modern terminal emulators should be all capable of rendering "True Colors". You should make sure to check out the great [“Terminal Colors“ gist][6] that provides many details about color rendering in terminal emulators, tracking of supported terminal emulator projects and answers to common confusions about terminal colors. The [“Colours in terminal“ gist][7] is also quite helpful to learn more about the actual rendering engines and standards used by these terminal emulators.
There are also a lot of blog posts like [this][4] and [this][5] one that help to handle different use case with various terminal emulators in combination with different CLI and TUI applications.

Could you please try to either use the example configuration or set the `termguicolors` setting in your current configuration and check whether colors are then displayed correctly?

[3]: https://github.com/junegunn/vim-plug
[4]: https://sts10.github.io/2016/06/15/true-hex-colors-in-vim-with-iterm2.html
[5]: https://tomlankhorst.nl/iterm-tmux-vim-true-color
[6]: https://gist.github.com/XVilka/8346728
[7]: https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9
[8]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L37-L49
[9]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L19-L35
[10]: https://sw.kovidgoyal.net/kitty
[11]: https://en.wikipedia.org/wiki/Terminfo
[12]: https://gist.github.com/XVilka/8346728

**Comment by arcticicestudio** [comment]
@IronSideSec Have you been able to solve the problem? If yes it would be nice if you could summarize your solution to help others who are facing the same problem.

**Comment by arcticicestudio** [comment]
Closing this issue for now due to inactivity, but feel free to reply if you have time again or if there are still open problems.
