### ISSUE TITLE
Neovim lsp warning message is not using nord-13

### ISSUE THREAD

**Issue by marcushwz** [arcticicestudio/nord-vim#267]
I have recently update `nord-vim` and I realize the warning message is no longer using nord-13.

![image](https://user-images.githubusercontent.com/40255418/125238367-b7aa2200-e319-11eb-8abb-f54f5b472cf5.png)

**Comment by arcticicestudio** [comment]
Hi @marcushwz :wave:, thanks for your contribution :+1:

I guess you're running [version 0.17.0][1] which [introduced support for `nvim-treesitter`][2]. Like mentioned in the changelog this was the first implementation iteration and inconsistencies, compared to the current highlighting when using “normal“ Vim plugins per language, are expected so your report is very welcome.

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][3]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

I've quickly checked the LSP definition and the [`LspDiagnosticsDefaultWarning` group is defined to use `nord13`][4] so I'm not quite sure if tree-sitter maybe takes precedence with another highlighting group, but [`TSWarning` is also lined to the `Todo` group][5] which uses `nord13` too.

Can you also please check which group is shown when you move the cursor to the detected element and execute `:TSHighlightCapturesUnderCursor`?

[1]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.17.0
[2]: https://github.com/arcticicestudio/nord-vim/pull/253
[3]: https://github.com/junegunn/vim-plug
[4]: https://github.com/arcticicestudio/nord-vim/blob/8d8b9bf/colors/nord.vim#L577
[5]: https://github.com/nvim-treesitter/nvim-treesitter/blob/054c2a57/plugin/nvim-treesitter.vim#L89

**Comment by marcushwz** [comment]
Hi @arcticicestudio, thank you so much for the quick reply. I am still using `vim-polygot` for the syntax highlighting, so I can't really check `:TSHighlightCapturesUnderCursor`.

I give it a try for minimal configuration as below, but the problem still persists.
```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord

lua require('marcus.lsp')
```

**Comment by arcticicestudio** [comment]
Large frameworks/plugin collections like `vim-polygot` are often known to cause problems when mixed with other plugins due to the heavy amount of plugins and the order how the code is parsed and loaded. When the problem does not occur when running the minimal configuration it is likely that this is caused by this plugin.

**Comment by marcushwz** [comment]
For my minimal configuration, I do not include `vim-polygot`, but the highlighting for Warning is still using the wrong color. As per the configuration above, I have only included `nord-vim` and `nvim-lspconfig`. I will try and see if reverting back to previous commit helps.

**Comment by marcushwz** [comment]
@arcticicestudio, I have figured it out. So sorry, I think I am confused with the difference between `warning, information and hint` diagnostics. Seems like the above diagnostics falls under the `hint` categories, that's why it's not using `nord-13`. I will just change it myself :) Thanks for guiding me though!

**Comment by arcticicestudio** [comment]
To be true, I would have also classified it as a warning. At least this is the case for all of my ESLint setups.
Anyway, thanks for your tests and feedback 👍🏻
