### ISSUE TITLE
Aggressive error highlight with Treesitter

### ISSUE THREAD

**Issue by georg3tom** [arcticicestudio/nord-vim#269]
Significant parts of the code bg gets highlighted in red because of syntax errors.

![2021Jul23::015333](https://user-images.githubusercontent.com/22193688/126706481-bee2564c-8aa7-4d44-b666-794065809899.png)

Occurs only when treesitter highlight is enabled
NVIM v0.5.0 with latest nvim-treesitter

**Comment by tgturner** [comment]
I am also experiencing this issue when using Treesitter with nvim. 

It looks like the `TSError` highlighting group should be removed. You can see how the Dracula theme handled it [here](https://github.com/dracula/vim/pull/232). I would submit a PR but I'm not currently at a computer I can commit from.

**Comment by georg3tom** [comment]
I'll open a PR

**Comment by arcticicestudio** [comment]
Hi @georg3tom and @tgturner :wave:, thanks for your contributions :+1:

Based on the references it looks like removing the group is currently the only solution to get rid of this, but I wonder how errors are then highlighted (if at all)? Will [Neovim's LSP][1] take over to only highlight the matched elements with the correct style (i.e. only change the foreground color of a single word) or will errors will appear the same like any other element and only messages from linters (maybe with arrow marker) will indicate that there is an error at all?

I have no problem removing the group, but I would just like to understand how this affects the user experience because I don't Neovim for active development (yet) and don't have a running setup yet to test this change.

[1]: https://github.com/neovim/nvim-lspconfig

**Comment by tgturner** [comment]
Hey @arcticicestudio this change does not impact Neovim’s LSP error highlighting (which still works correctly) but only impacts Treesitter (Neovim’s improved syntax highlighting) error highlights.

since Treesitter is constantly parsing the file, when typing you are pretty much garunteed to have invalid syntax the Treesitter can’t parse at points. It looks like most themes are not relying on Treesitter’s error groups because of this issue, but offloading the work to linters and LSP client to report syntax errors. I’m not currently at my computer but would be happy to paste an image of what LSP error highlighting looks like after the proposed change.

**Comment by arcticicestudio** [comment]
Thanks @tgturner, when LSP takes care of it we can remove the group without having to worry. I'll merge #270 to get this into the [next release][1] version [0.18.0][2] with ETA for tomorrow (2021-09-07).

[1]: https://github.com/arcticicestudio/nord-vim/projects/24
[2]: https://github.com/arcticicestudio/nord-vim/milestone/20?closed=1
