### ISSUE TITLE
weird background in coc.nvim warnings/errors

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [arcticicestudio/nord-vim#274]
Hi, there seems to be a problem with the background of the coc.nvim warnings and errors.
The background is a weird teal, not the original Nord theme background.
I've added screenshots of **both** warnings and errors in coc.nvim.

Background Info:
- Neovim Version: Neovim v0.6.0-dev
- Terminal Emulator: Windows Terminal
- OS: Ubuntu-20.04 on WSL2 (*Edit*: I have also tried on a Virtual Machine running Ubuntu 20.04. The background for coc warnings and errors is the same weird turquoise color)

**Regular Config**
![image](https://user-images.githubusercontent.com/79387351/130346371-5990fcb6-e240-47d4-a117-659591b8c64d.png)
![image](https://user-images.githubusercontent.com/79387351/130346390-3641aa20-ff1f-48de-966b-bcecf92a3c48.png)

**Minimal Config**
`~/.config/nvim/init.vim`:
![image](https://user-images.githubusercontent.com/79387351/131099404-269d9779-93c4-467c-bb46-cc571788ad23.png)

![image](https://user-images.githubusercontent.com/79387351/131099533-9194f181-2695-46f6-8129-f248bc2fa62b.png)
![image](https://user-images.githubusercontent.com/79387351/131099603-56c67eef-5d44-4a29-b7df-573c4b50f016.png)

Let me know if any other information is needed.

**Comment by arcticicestudio** [comment]
Hi @g-e-o-m-e-t-r-i-c :wave:, thanks for your contribution :+1:
Thanks for the detailed report and reproduction steps!

This looks like a problem with the setup of the Nord colors for your terminal. There is currently no official port project for the new “Windows Terminal“ so I'm not sure which one you installed (or defined on your own).
Maybe there is a problem with the color space used by the terminal so adding the following to the configuration might help:

```vim
set nocompatible
if (has("termguicolors"))
  set termguicolors
endif
```

This will enable 24-bit color support instead of only relying on the colors defined as theme by the terminal.

**Comment by g-e-o-m-e-t-r-i-c** [comment]
It is fixed now.

**Comment by arcticicestudio** [comment]
Nice to see that it works for you know. Can you please post a short description what exactly fixed the problem so other users who read this issue can also solve the problem?

**Comment by g-e-o-m-e-t-r-i-c** [comment]
I'm using Windows Terminal, so I found an **unofficial** port of the Nord theme on https://windowsterminalthemes.dev/.
I also use Neovim, so I used this script to enable TrueColor (before enabling the Nord theme):
```
if (has("nvim"))
	let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
if (has("termguicolors"))
	set termguicolors
endif
```
