### ISSUE TITLE
Question: Missing line numbers and other visual differences

### ISSUE THREAD

**Issue by Tooa** [arcticicestudio/nord-vim#275]
Hi @arcticicestudio,

I installed the `nord-vim` plugin as described in the given instructions. Though, I wonder about a few visual differences between my installation and the provided screenshots. Maybe you can help me out here.

1. I miss the line numbers. Doesn't the plugin enable them or was it enabled using `set number` just for the screenshots? 
2. My syntax highlighting does not seem to use a bold font when comparing it to the provided screenshots
3. I am missing the status bar indicating the file opened, the encoding, etc. Is this another plugin or `tmux`?

Thanks for the help! Let me know if you need more information.

![nord-vim-gnome](https://user-images.githubusercontent.com/5375334/130859431-2dc4ba9e-8f72-4a15-bf0e-ea242012dd17.png)
![nord-vim-gnome-2](https://user-images.githubusercontent.com/5375334/130860839-bbd26376-a0db-495a-9d6e-f9a3b2d11f90.png)

## Details

* Ubuntu 21.04 with cinnamon desktop
* Nord gnome terminal port installed and profile enabled
* SourceCode-Pro font installed
* Nord dircolors installed
* No tmux enabled for testing
* Minimal `~/.vimrc` as below
```bash
call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim'
call plug#end()

colorscheme nord
```

**Comment by arcticicestudio** [comment]
Hi @Tooa :wave:

1. **Missing line numbers** — The installation instructions are only scoped to the actual setup steps for the theme while some screenshots are just examples what the applied theme can look like. Basically themes should never mess around with settings like line numbers but only focus on color highlighting. In order to show line numbers you need to set the `number` option in your configuration:
   ```vim
   set number
   ```
2. **Bold font styles** — for special font styles like **bold** your terminal must be capable of rendering these styles, but most modern terminals today provide this feature by default. Nord enables bold styles by default, but you can disable it by [setting the `nord_bold` theme variable to `0`][1]:
   ```vim
   let g:nord_bold = 0
   ```
3. **Status bar** — Like already mentioned in list item `1` most screenshots of Vim themes (and other applications) are often mainly used for demonstration purposes and require a little basic knowledge of what belongs to the theme and what does not. In this case the status bar is a supported plugin called [lightline.vim][2]. Nord Vim comes with [dedicated support for this plugin][3], but the installation of the plugin itself is not something Nord is responsible for but must be done on the user side.

[1]: https://www.nordtheme.com/docs/ports/vim/configuration#bold-style
[2]: https://github.com/itchyny/lightline.vim
[3]: https://github.com/arcticicestudio/nord-vim/blob/d30ea87f/autoload/lightline/colorscheme/nord.vim

**Comment by arcticicestudio** [comment]
@Tooa Do you had the time to test the recommended configurations already?

**Comment by Tooa** [comment]
Hi @arcticicestudio,

sorry for the late answer and thanks for your detailed response.

1. **Missing line numbers** —  Following your suggestion, I added `set numbers` to my `.vimrc`. 
2. **Bold font styles** — I assume Nord gnome terminal port is capable of rendering these styles.
3. **Status bar** — Thanks for pointing that out. I installed `lightline` and configured `nord` as `colorscheme`. It now looks like the provided screenshots.

Can you tell the font of the screenshots?

**Comment by arcticicestudio** [comment]
So I guess the only open question is **2** and I can't see any reason why bold font styles shouldn't work. Looking at the marker on your first screenshot the folders look like they are bold. Also the "Nord GNOME Terminal" port project is not responsible for any rendering tasks but only defines a custom color profile. The rendering engine of GNOME Terminal is modern so bold font styles should definitely work.

The font family is [Source Code Pro][1] (medium weight) so that's the one you also configured already.

[1]: https://github.com/adobe-fonts/source-code-pro

**Comment by arcticicestudio** [comment]
@Tooa Have you been able to solve the problem? If yes it would be nice if you could summarize your solution to help others who are facing the same problem.

**Comment by arcticicestudio** [comment]
Closing this issue since all questions should be answered.
