### ISSUE TITLE
comments are hardly seen

### ISSUE THREAD

**Issue by ZigZag35** [arcticicestudio/nord-vim#281]
I'm using st terminal with a nord0 background.
comments are hardly seen.

![Screenshot_2021-11-20_16-48-26](https://user-images.githubusercontent.com/67876743/142734429-68564851-180e-45af-aabd-79e13a266ab9.png)

**Comment by arcticicestudio** [comment]
Hi @ZigZag35 :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

This is because, like described in arcticicestudio/nord#94, the actual color palette hasn't changed but only ports that are targeted to applications with syntax highlighting.

As you can see in the example configuration I've added the `termguicolors` settings which could be one reason why the color is not rendered correctly. This is because the [`*_term` attributes][gh-blob-term_attr] make use of the colors that are provided by the terminal color scheme which might be for example [iTerm2][ref-iterm] or [Tilix][ref-tilix]. The [`*_gui` variables][gh-blob-gui_attr] on the other side are used when Vim runs in GUI mode. So in order to run Vim in a terminal but use colors like in GUI mode the `termguicolors` variable must be set and your terminal emulator must support “true colors“ (24bit).

Unfortunately terminal colors are quite complex due to their long history, but modern terminal emulators should be all capable of rendering "True Colors". You should make sure to check out the great [“Terminal Colors“ gist][gist-tc] that provides many details about color rendering in terminal emulators, tracking of supported terminal emulator projects and answers to common confusions about terminal colors. The [“Colours in terminal“ gist][gist-cit] is also quite helpful to learn more about the actual rendering engines and standards used by these terminal emulators.
There are also a lot of blog posts like [this][bp1] and [this][bp2] one that help to handle different use case with various terminal emulators in combination with different CLI and TUI applications.

Could you please try to either use the example configuration or set the `termguicolors` setting in your current configuration and check whether colors are then displayed correctly?

[ref-tilix]: https://github.com/arcticicestudio/nord-tilix/blob/ce9c46ecd3d7b0d49d6cb4b99e092f7df6b9a48c/src/json/nord.json
[ref-iterm]: https://github.com/arcticicestudio/nord-iterm2/blob/b334a9b4/src/xml/Nord.itermcolors#L187-L199
[vim-plug]: https://github.com/junegunn/vim-plug
[bp1]: https://sts10.github.io/2016/06/15/true-hex-colors-in-vim-with-iterm2.html
[bp2]: https://tomlankhorst.nl/iterm-tmux-vim-true-color
[gist-tc]: https://gist.github.com/XVilka/8346728
[gist-cit]: https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9
[gh-blob-term_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L37-L49
[gh-blob-gui_attr]: https://github.com/arcticicestudio/nord-vim/blob/ea7ff9c3/colors/nord.vim#L19-L35

**Comment by ZigZag35** [comment]
hello,
I should've added that I'm using neovim on st terminal emulator.
I've followed this page from the arch wiki: https://wiki.archlinux.org/title/st#256color_and_truecolor_support_not_working_in_tmux_or_otherwise 
my .nvimrc now has
```
set t_Co=256                         " Enable 256 colors
if (has("termguicolors"))
   set termguicolors
endif
```
C comments are displayed correctly now with/without tmux. 
the only difference is the bg color being more bright inside tmux but that isn't an issue.

Thank you for your support :D

**Comment by arcticicestudio** [comment]
Nice to hear that it works now and thanks for posting your solution. The problem with st in combination with Vim and tmux has been a problem reported often in this repository as well as the solution, but the link to the section of the Arch Linux wiki page is perfect to be included in the Nord Docs 👍🏼
