### ISSUE TITLE
Tank you for changing 'master' to 'main'...

### ISSUE THREAD

**Issue by p-kolacz** [arcticicestudio/nord-vim#317]
... and wasting 2h of my life on debugging my config file.

**Comment by svengreb** [comment]
Hi @p-kolacz :wave:

Even if I always like feedback, unfortunately there is absolutely no point in opening an issue that only contains a single and slightly sarcastic sentence but only ensures that further development is delayed due to maintenance overhead.

Anyway, I'm sorry that the theme update process broke on your side, but this is also something to expect when using a project's upstream branch instead of relying on stable version tags. [Nord Vim's “Installation“ documentation page][1] explicitly mentions and recommends to use a plugin/`runtimepath` manager which will automatically use the default branch of an repository **but will also ensure to update the reference when this upstream branch gets changed or renamed**. After taking a [quick look at your public _.dotfiles_ it looks like you've implemented a self-made plugin management solution][2] where the cost is often that things might break compared to more stable and battle-tested projects. In your case the repository was cloned locally once while the default branch was still `master` but it won't be updated when this reference changes. Nord Vim's documentation also mentions that most plugin managers allow to define a specific version tag instead of using the upstream default branch which is a best-practice in many development areas anyway.

The [actual change in this repository][3] is also something that [has been planned for a long time for all Nord projects][4]. This not something only done for Nord but a world-wide initiative that was started over 2 years ago and [even Git itself has changed the default branch name from `master` to `main`][5] as well as millions of other projects and of course [platforms like GitHub][6] and [GitLab][7].

In the end all I can say is that users who like to use the upstream of a project must also live with the risk of **possible** breaking changes and know how to deal with them on their own.

[1]: https://www.nordtheme.com/docs/ports/vim/installation
[2]: https://github.com/p-kolacz/.dotfiles/blob/e421103a3f33/nvim/.config/nvim/lua/lib/plugozaur.lua
[3]: https://github.com/arcticicestudio/nord-vim/pull/314
[4]: https://github.com/arcticicestudio/styleguide-git/issues/11
[5]: https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com
[6]: https://github.com/github/renaming
[7]: https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name
