### ISSUE TITLE
Underline doesn't work in windows terminal 

### ISSUE THREAD

**Issue by seudonam** [arcticicestudio/nord-vim#318]
No underline for diagnostics.
![Screenshot (2)](https://user-images.githubusercontent.com/36813942/173339136-7094faaa-20b3-48e8-bf7e-b3d9c8887af7.png)
If I delete`  if a:attr != ""
    let cmd = cmd . " gui=" . a:attr . " cterm=" . substitute(a:attr, "undercurl", s:underline, "")
  endif
`in nord.vim. Then I got underline but statusline changed somehow.
![Screenshot (3)](https://user-images.githubusercontent.com/36813942/173340027-652d544c-6b2f-4ed5-94bd-312533bf1632.png)

**Comment by seudonam** [comment]
I use neovim on windows 10.

**Comment by svengreb** [comment]
Hi @seudonam :wave:

Please see the [Nord Vim documentation page about underline styles][1] for details about why underlines are not enabled by default as well as the `g:nord_underline` theme configuration that allows to enable them.

[1]: https://www.nordtheme.com/docs/ports/vim/configuration#underline-style

**Comment by seudonam** [comment]
I added `let g:nord_underline = 1` before, but it doesn't work either.😭I think it's something wrong interacting with windows terminal cz underline works on Windows 10 with alacritty in default mode

**Comment by svengreb** [comment]
This is possible and the reason why underline styles are disabled by default like described in the Nord Vim docs:

> This design decision is based on the known problems of most terminals related to special font styles like underline.

But another reason could be that the Windows terminal is not marking itself as GUI and therefore Vim does not enable GUI specific features.
Please try to add the following to your Vim configuration:

```vim
if (has("termguicolors"))
  set termguicolors
endif
```

**Comment by seudonam** [comment]
@svengreb ☺
`set termguicolors`   is already added in init.vim befor. Actually the underline works when I didn't set this.

**Comment by svengreb** [comment]
Do you use any third-party C++ plugin/package for syntax highlighting other than the bundled one? If so it is possible that is overrides styles for this highlighting group.

Also I just saw that you mentioned that this is related to Neovim LSP diagnostics and the style defined by Nord does explicitly not make use of the `underline` attribute for the `DiagnosticUnderlineWarn` syntax group:

https://github.com/arcticicestudio/nord-vim/blob/bc0f057162491e9228207d74bd88b5efe875316e/colors/nord.vim#L191

So my guess is that this is by design, but to make sure it would be nice of you could [identify the syntax highlighting group used at the cursor][1] where you are missing the underline. 

[1]: https://vim.fandom.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

**Comment by seudonam** [comment]
updated to neovim 8.0 and underline is ok !
