### ISSUE TITLE
Weird Syntax Highlighting for neovim

### ISSUE THREAD

**Issue by CopernicusPY** [arcticicestudio/nord-vim#319]
I installed the vim plugin for neovim using vim-plug as the plugin manager. 
When I set the color scheme to `nord` I get a completly different color scheme than the default one that the docs show. I also use the lightline plugin and it also gets styled with that weird color scheme.
 I removed and re-installed neovim and nord, but same results.

(Also some languages such as go are not highlighted)

Here is a photo of how it looks 
[results that i get](https://imgur.com/a/c5ktx9K)

**Comment by CopernicusPY** [comment]
Its weird, that I copied the nord.vim file directly from this repository, and added it in my themes folder and setted it as the colorscheme (Had removed the nord plugin first to avoid problems). Same thing . . . Seems that with [nord.nvim](https://github.com/shaunsingh/nord.nvim) it gives me the syntax highlighting and colorscheme in general that the docs showed.

**Comment by svengreb** [comment]
Hi @CopernicusPY :wave:

Like [mentioned in the Reddit post][1] (just to give some context for others reading this issue) my guess about an invalid local setup seem to be correct. The [blue box at the top of Nord Vim's "Installation & Activation" guide][2] informs that the matching terminal theme must be present because Vim uses the 16 ANSI base colors provided by the terminal in which it is running. Based on your screenshot (by the way, you can simply [upload images & videos directly to most content fields on GitHub][4]) this doesn't seem to be the case. Since you haven't provided any additional information about your system I can't recommended a specific Nord port so please make sure to check if you terminal is supported through any of [Nord's official ports][3] or, if not, maybe a port created by the community.

The answer to why the Neovim specific theme port works is also simple (and partly answered in the Reddit thread): This theme is for "Vanilla" Vim while Neovim is not supported explicitly but only when it runs Vim specific plugins. The fact that it "just works" without the need to have the matching terminal theme installed is simply because [Neovim natively supports hexadecimal color codes ("true color", ISO-8613-3 compatible terminals)][5] which will be used as is instead of relying on the terminal to translate the requested ANSI color code to the matching hexadecimal color so [the third-party Neovim Nord port can simply define the color palette like this][6].

[1]: https://www.reddit.com/r/nordtheme/comments/vlrw1p/comment/idyxsnw/?utm_source=share&utm_medium=web2x&context=3
[2]: https://www.nordtheme.com/docs/ports/vim/installation
[3]: https://www.nordtheme.com/ports
[4]: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
[5]: https://neovim.io/doc/user/options.html#'termguicolors'
[6]: https://github.com/shaunsingh/nord.nvim/blob/master/lua/nord/named_colors.lua

**Comment by CopernicusPY** [comment]
Yes, I understand. By the way, I am using QTerminal since it is the default terminal emulator on the kali distro. I searched through the nord official/un-official port projects but seems there isn't one for QTerminal. I think I can safely close this issue by saying that I prefer keep using the third party theme, until full support comes for neovim. Thank you

**Comment by svengreb** [comment]
QTerminal, and the LXQt project in general, is indeed nothing that Nord explicitly supports yet, but when there is a higher demand it might be a possible candidate when active port developments gets started again. I've added it to one of the project boards/tables that will also be made public within the next weeks.

**Comment by CopernicusPY** [comment]
Yeah thats great. I would switch to alacritty ( i have it installed with nord as its colorscheme), I just really hate the need of using 3rd party apps to allow multiple instances/tabs screen splits etc.
