### ISSUE TITLE
Cursor disappear when using substitute command

### ISSUE THREAD

**Issue by KevinSjoberg** [arcticicestudio/nord-vim#35]
Running `:%s/target/replacement/gc` will make the cursor disappear. This is due to the highlight group`Search` and `IncSearch` having identical colors. [Base16 had an identical issue](https://github.com/chriskempson/base16-vim/issues/124) and it was resolved in https://github.com/chriskempson/base16-vim/pull/129.

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
Sorry for my late reply, I've been busy with my job.

The linked PR in the base16 repository only changed the foreground- and background color to be different for the `Search` and `IncSearch` groups, but the cursor is still not visible because the focus is in the command bar.

Can you check out #39 which fixes the unreadable foreground color for pending search results. Maybe it makes this issue obsolete.

Another solution would be to set the `underline` attribute for the `IncSearch` groups which would underline the currently active highlight.

![gh-35-scrcast-underline-highlight](https://user-images.githubusercontent.com/7836623/28245896-ebd3abae-6a10-11e7-9e83-85b69cb62455.gif)
