### ISSUE TITLE
Difficult to read comments due to contrast with background

### ISSUE THREAD

**Issue by scottwillmoore** [arcticicestudio/nord-vim#6]
To my knowledge there is no simple solution, but I thought I would ask just in case.

I find comments difficult to read due to the low contrast between the comment and background colours. I was wondering if this could be fixed in a similar manner as the solarized theme, with `g:solarized_contrast="high"`.

I believe this is possible, the *real* question is, what colour should be substituted. Unfortunately the 16-colour palate does not contain a lighter shade of grey!

The only possible solution I could suggest would be to use a 256-colour fallback. However, none of these appear to be a suitable "blue/grey" colour to replace the original.

Another option would be to "personalise" the 16-colour palate, by adjusting the grey.

Would appreciate your thoughts, thanks!

**Comment by arcticicestudio** [comment]
Comments are specially designed in the Nord style guideline to be non obstructive and keep the focus on the code. I've never had problems to read comments actually low contrast is even better for the eyes compared to too bright colors.

The problem with Nord Vim is the limit of the 16 colors. I have [deliberately decided against the 256 color palette](https://github.com/arcticicestudio/nord-vim/issues/1) to keep it faithful to the Nord design guideline since the 256 colorspace limits the possibility to create the same ambient and does not provide the necessary color shades.

I think color adjustments should be done manually by every user if they wish to modify the theme to fit their own needs.

**Comment by scottwillmoore** [comment]
Yep I agree. After using Nord for a while now, the comment colour has worn on me. I think it was just a bit startling coming from my old colorscheme, where the comments were extremely easy to read.

It is just readable on my primary monitor, however my secondary monitor, which is slightly further away (and on a slight angle) can make it difficult to read.

I'll give myself some time to get used to the colour, otherwise at least I have the power to change it manually. Thanks anyway! :smile:
