### ISSUE TITLE
wrong background when using neovim + termguicolors + tmux

### ISSUE THREAD

**Issue by sdemura** [arcticicestudio/nord-vim#72]
When using `set tgc` on Neovim so that I can take advantage of comment brightness, I get the wrong background color when using it inside tmux.

OS X High Sierra
iTerm2 3.1.5 (xterm-256color)
Tmux 2.6 (screen-256color)
neovim 0.2.1 (tgc set)

running in tmux:
<img width="815" alt="screen shot 2017-11-17 at 9 27 05 am" src="https://user-images.githubusercontent.com/11758459/32952119-3c781f02-cb7a-11e7-9909-3f081d8691f8.png">

no tmux:
<img width="787" alt="screen shot 2017-11-17 at 9 26 54 am" src="https://user-images.githubusercontent.com/11758459/32952122-3ebb4da2-cb7a-11e7-8a03-be348641b4db.png">

**Comment by arcticicestudio** [comment]
Please try to fix it by following the instructions in https://github.com/arcticicestudio/nord-tmux/issues/15#issuecomment-341715220.

**Comment by sdemura** [comment]
@arcticicestudio,
adding `+set-option -ga terminal-overrides ",xterm-256color:Tc"` to my tmux.conf did the trick.

Thanks!!!!

**Comment by arcticicestudio** [comment]
Glad to hear it worked :smile: 

I'll add a chapter about the usage with *tmux* to the documentation.

**Comment by i3d** [comment]
the original wasn't working for me
"+set-option -ga terminal-overrides ",xterm-256color:Tc"

But this did
"set -ga terminal-overrides ",xterm-256color:Tc"

1. paste the set command within the quote verbatimly into your .tmux.conf. (append to the end, so that it is the last set option to execute, override any other ones possible)
2. tmux source ~/.tmux.conf
3. try again, it should work.
