### ISSUE TITLE
Contrast of brackets is counterintuitive

### ISSUE THREAD

**Issue by vincentzhezhang** [arcticicestudio/nord-vim#75]
The contrast (or colour intensity) for brackets under the cursor annoyed me a lot recently.
The problem as you can see from the screenshots below is: when you moving the cursor, the bracket will blink between frame 1 and frame 2. Even worse, frame 1 comes first and has a darker colour without other visual indications. So my eyes are distracted to focus on the matching bracket instead of the bracket at the cursor position.

![image](https://user-images.githubusercontent.com/1330120/33055505-0da76c16-cebb-11e7-8425-9a15b5f6bfec.png)
Nord bracket under cursor frame 1
![image](https://user-images.githubusercontent.com/1330120/33055531-3b8ed650-cebb-11e7-8e5c-4e69e2cd28a9.png)
Nord bracket under cursor frame 2

In contrast, Gruvbox set it in a more intuitive way:

![image](https://user-images.githubusercontent.com/1330120/33055695-097d43da-cebc-11e7-8f3f-8659bcdfbf5a.png)
Gruvbox bracket under cursor frame 1
![image](https://user-images.githubusercontent.com/1330120/33055668-e78d9c02-cebb-11e7-9da7-4d2298d2b0e3.png)
Gruvbox bracket under cursor frame 2

Probably you guys could consider updating the colour a bit? 
Thank you for making such a great suites of colour schemes!

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1:  and sorry for my late reply.

I've been a bit confused about the light border around the matching bracket on the *frame 1* screenshot of the Gruvbox theme. I've checked their code and the vim documentations again to see if I never noticed that Vim supports borders for elements which would solve the problem immediately, but then I recognized that it is just the `Block` cursor type instead of `IBeam` which is shown as a empty box when the terminal is not focused :laughing: 

Anyway, I've posted my review of your PR in #78.
